server:
  port: 10041
spring:
  application:
    name: spring-boot-elasticsearch
  elasticSearch:
    cluster-name: ${ES_CLUSTER_NAME:elastic}
    host: ${ES_HOST:10.31.63.96}
    port: ${ES_PORT:9200}
    scheme: http
    auth-enable: true
    user:
      name: ${ES_USER:elastic}
      password: ${ES_PASSWORD:unpaouqKm0BQ}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://10.31.63.16:3306/cp_rd}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:iztNN49c5B}
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      kill-when-socket-read-timeout: true
      fail-fast: true

  redis:
    cluster:
      nodes: ${REDIS_NODES:10.31.63.48:6379,10.31.63.49:6379,10.31.63.50:6379,10.31.63.51:6379,10.31.63.52:6379,10.31.63.53:6379}
    password: ${REDIS_PASSWORD:HkxuxW0Xsg}
    lettuce:
      pool:
        max-idle: 96
        max-wait: -1
        max-active: -1
        min-idle: 48
