server:
  port: 10041
spring:
  application:
    name: spring-boot-elasticsearch
  elasticSearch:
    cluster-name: ${ES_CLUSTER_NAME:elastic}
    host: ${ES_HOST:10.31.63.96}
    port: ${ES_PORT:9200}
    scheme: http
    auth-enable: true
    user:
      name: ${ES_USER:elastic}
      password: ${ES_PASSWORD:unpaouqKm0BQ}


